-- Add migration script here
-- well... that was a failed experiment
alter table game_player_stats
    drop column if exists allowed_stolen_bases,
    drop column if exists allowed_stolen_bases_risp,
    drop column if exists appearances,
    drop column if exists assists,
    drop column if exists assists_risp,
    drop column if exists at_bats,
    drop column if exists at_bats_risp,
    drop column if exists balks,
    drop column if exists balks_risp,
    drop column if exists batters_faced,
    drop column if exists batters_faced_risp,
    drop column if exists blown_saves,
    drop column if exists caught_double_play,
    drop column if exists caught_double_play_risp,
    drop column if exists caught_stealing,
    drop column if exists caught_stealing_risp,
    drop column if exists complete_games,
    drop column if exists double_plays,
    drop column if exists double_plays_risp,
    drop column if exists doubles,
    drop column if exists doubles_risp,
    drop column if exists earned_runs,
    drop column if exists earned_runs_risp,
    drop column if exists errors,
    drop column if exists errors_risp,
    drop column if exists field_out,
    drop column if exists field_out_risp,
    drop column if exists fielders_choice,
    drop column if exists fielders_choice_risp,
    drop column if exists flyouts,
    drop column if exists flyouts_risp,
    drop column if exists force_outs,
    drop column if exists force_outs_risp,
    drop column if exists games_finished,
    drop column if exists grounded_into_double_play,
    drop column if exists grounded_into_double_play_risp,
    drop column if exists groundout,
    drop column if exists groundout_risp,
    drop column if exists groundouts,
    drop column if exists groundouts_risp,
    drop column if exists hit_batters,
    drop column if exists hit_batters_risp,
    drop column if exists hit_by_pitch,
    drop column if exists hit_by_pitch_risp,
    drop column if exists hits_allowed,
    drop column if exists hits_allowed_risp,
    drop column if exists home_run_challenge_appearances,
    drop column if exists home_run_challenge_home_runs,
    drop column if exists home_run_challenge_home_runs_allowed,
    drop column if exists home_runs,
    drop column if exists home_runs_allowed,
    drop column if exists home_runs_allowed_risp,
    drop column if exists home_runs_risp,
    drop column if exists inherited_runners,
    drop column if exists inherited_runners_risp,
    drop column if exists inherited_runs_allowed,
    drop column if exists inherited_runs_allowed_risp,
    drop column if exists left_on_base,
    drop column if exists left_on_base_risp,
    drop column if exists lineouts,
    drop column if exists lineouts_risp,
    drop column if exists losses,
    drop column if exists mound_visits,
    drop column if exists no_hitters,
    drop column if exists outs,
    drop column if exists perfect_games,
    drop column if exists pitches_thrown,
    drop column if exists pitches_thrown_risp,
    drop column if exists plate_appearances,
    drop column if exists plate_appearances_risp,
    drop column if exists popouts,
    drop column if exists popouts_risp,
    drop column if exists putouts,
    drop column if exists putouts_risp,
    drop column if exists quality_starts,
    drop column if exists reached_on_error,
    drop column if exists reached_on_error_risp,
    drop column if exists runners_caught_stealing,
    drop column if exists runners_caught_stealing_risp,
    drop column if exists runs,
    drop column if exists runs_batted_in,
    drop column if exists runs_batted_in_risp,
    drop column if exists runs_risp,
    drop column if exists sac_flies,
    drop column if exists sac_flies_risp,
    drop column if exists sacrifice_double_plays,
    drop column if exists sacrifice_double_plays_risp,
    drop column if exists saves,
    drop column if exists shutouts,
    drop column if exists singles,
    drop column if exists singles_risp,
    drop column if exists starts,
    drop column if exists stolen_bases,
    drop column if exists stolen_bases_risp,
    drop column if exists strikeouts,
    drop column if exists strikeouts_risp,
    drop column if exists struck_out,
    drop column if exists struck_out_risp,
    drop column if exists triples,
    drop column if exists triples_risp,
    drop column if exists unearned_runs,
    drop column if exists unearned_runs_risp,
    drop column if exists walked,
    drop column if exists walked_risp,
    drop column if exists walks,
    drop column if exists walks_risp,
    drop column if exists wins;

drop materialized view if exists game_player_stats_exploded cascade;

create table game_player_stats_exploded(
    game_id text not null,
    team_id text not null,
    player_id text not null,
    season smallint,
    day smallint,
    player_name text,
    allowed_stolen_bases smallint,
    allowed_stolen_bases_risp smallint,
    appearances smallint,
    assists smallint,
    assists_risp smallint,
    at_bats smallint,
    at_bats_risp smallint,
    balks smallint,
    balks_risp smallint,
    batters_faced smallint,
    batters_faced_risp smallint,
    blown_saves smallint,
    caught_double_play smallint,
    caught_double_play_risp smallint,
    caught_stealing smallint,
    caught_stealing_risp smallint,
    complete_games smallint,
    double_plays smallint,
    double_plays_risp smallint,
    doubles smallint,
    doubles_risp smallint,
    earned_runs smallint,
    earned_runs_risp smallint,
    errors smallint,
    errors_risp smallint,
    field_out smallint,
    field_out_risp smallint,
    fielders_choice smallint,
    fielders_choice_risp smallint,
    flyouts smallint,
    flyouts_risp smallint,
    force_outs smallint,
    force_outs_risp smallint,
    games_finished smallint,
    grounded_into_double_play smallint,
    grounded_into_double_play_risp smallint,
    groundout smallint,
    groundout_risp smallint,
    groundouts smallint,
    groundouts_risp smallint,
    hit_batters smallint,
    hit_batters_risp smallint,
    hit_by_pitch smallint,
    hit_by_pitch_risp smallint,
    hits_allowed smallint,
    hits_allowed_risp smallint,
    home_run_challenge_appearances smallint,
    home_run_challenge_home_runs smallint,
    home_run_challenge_home_runs_allowed smallint,
    home_runs smallint,
    home_runs_allowed smallint,
    home_runs_allowed_risp smallint,
    home_runs_risp smallint,
    inherited_runners smallint,
    inherited_runners_risp smallint,
    inherited_runs_allowed smallint,
    inherited_runs_allowed_risp smallint,
    left_on_base smallint,
    left_on_base_risp smallint,
    lineouts smallint,
    lineouts_risp smallint,
    losses smallint,
    mound_visits smallint,
    no_hitters smallint,
    outs smallint,
    perfect_games smallint,
    pitches_thrown smallint,
    pitches_thrown_risp smallint,
    plate_appearances smallint,
    plate_appearances_risp smallint,
    popouts smallint,
    popouts_risp smallint,
    putouts smallint,
    putouts_risp smallint,
    quality_starts smallint,
    reached_on_error smallint,
    reached_on_error_risp smallint,
    runners_caught_stealing smallint,
    runners_caught_stealing_risp smallint,
    runs smallint,
    runs_batted_in smallint,
    runs_batted_in_risp smallint,
    runs_risp smallint,
    sac_flies smallint,
    sac_flies_risp smallint,
    sacrifice_double_plays smallint,
    sacrifice_double_plays_risp smallint,
    saves smallint,
    shutouts smallint,
    singles smallint,
    singles_risp smallint,
    starts smallint,
    stolen_bases smallint,
    stolen_bases_risp smallint,
    strikeouts smallint,
    strikeouts_risp smallint,
    struck_out smallint,
    struck_out_risp smallint,
    triples smallint,
    triples_risp smallint,
    unearned_runs smallint,
    unearned_runs_risp smallint,
    walked smallint,
    walked_risp smallint,
    walks smallint,
    walks_risp smallint,
    wins smallint,
    primary key (game_id, team_id, player_id)
);

-- one time insert
insert into game_player_stats_exploded (
    season,
    day,
    game_id,
    player_id,
    team_id,
    player_name,
    
    allowed_stolen_bases,
    allowed_stolen_bases_risp,
    appearances,
    assists,
    assists_risp,
    at_bats,
    at_bats_risp,
    balks,
    balks_risp,
    batters_faced,
    batters_faced_risp,
    blown_saves,
    caught_double_play,
    caught_double_play_risp,
    caught_stealing,
    caught_stealing_risp,
    complete_games,
    double_plays,
    double_plays_risp,
    doubles,
    doubles_risp,
    earned_runs,
    earned_runs_risp,
    errors,
    errors_risp,
    field_out,
    field_out_risp,
    fielders_choice,
    fielders_choice_risp,
    flyouts,
    flyouts_risp,
    force_outs,
    force_outs_risp,
    games_finished,
    grounded_into_double_play,
    grounded_into_double_play_risp,
    groundout,
    groundout_risp,
    groundouts,
    groundouts_risp,
    hit_batters,
    hit_batters_risp,
    hit_by_pitch,
    hit_by_pitch_risp,
    hits_allowed,
    hits_allowed_risp,
    home_run_challenge_appearances,
    home_run_challenge_home_runs,
    home_run_challenge_home_runs_allowed,
    home_runs,
    home_runs_allowed,
    home_runs_allowed_risp,
    home_runs_risp,
    inherited_runners,
    inherited_runners_risp,
    inherited_runs_allowed,
    inherited_runs_allowed_risp,
    left_on_base,
    left_on_base_risp,
    lineouts,
    lineouts_risp,
    losses,
    mound_visits,
    no_hitters,
    outs,
    perfect_games,
    pitches_thrown,
    pitches_thrown_risp,
    plate_appearances,
    plate_appearances_risp,
    popouts,
    popouts_risp,
    putouts,
    putouts_risp,
    quality_starts,
    reached_on_error,
    reached_on_error_risp,
    runners_caught_stealing,
    runners_caught_stealing_risp,
    runs,
    runs_batted_in,
    runs_batted_in_risp,
    runs_risp,
    sac_flies,
    sac_flies_risp,
    sacrifice_double_plays,
    sacrifice_double_plays_risp,
    saves,
    shutouts,
    singles,
    singles_risp,
    starts,
    stolen_bases,
    stolen_bases_risp,
    strikeouts,
    strikeouts_risp,
    struck_out,
    struck_out_risp,
    triples,
    triples_risp,
    unearned_runs,
    unearned_runs_risp,
    walked,
    walked_risp,
    walks,
    walks_risp,
    wins
)
    select
        season, day, game_id, player_id, team_id, player_name,
        (data->'allowed_stolen_bases')::smallint as allowed_stolen_bases,
        (data->'allowed_stolen_bases_risp')::smallint as allowed_stolen_bases_risp,
        (data->'appearances')::smallint as appearances,
        (data->'assists')::smallint as assists,
        (data->'assists_risp')::smallint as assists_risp,
        (data->'at_bats')::smallint as at_bats,
        (data->'at_bats_risp')::smallint as at_bats_risp,
        (data->'balks')::smallint as balks,
        (data->'balks_risp')::smallint as balks_risp,
        (data->'batters_faced')::smallint as batters_faced,
        (data->'batters_faced_risp')::smallint as batters_faced_risp,
        (data->'blown_saves')::smallint as blown_saves,
        (data->'caught_double_play')::smallint as caught_double_play,
        (data->'caught_double_play_risp')::smallint as caught_double_play_risp,
        (data->'caught_stealing')::smallint as caught_stealing,
        (data->'caught_stealing_risp')::smallint as caught_stealing_risp,
        (data->'complete_games')::smallint as complete_games,
        (data->'double_plays')::smallint as double_plays,
        (data->'double_plays_risp')::smallint as double_plays_risp,
        (data->'doubles')::smallint as doubles,
        (data->'doubles_risp')::smallint as doubles_risp,
        (data->'earned_runs')::smallint as earned_runs,
        (data->'earned_runs_risp')::smallint as earned_runs_risp,
        (data->'errors')::smallint as errors,
        (data->'errors_risp')::smallint as errors_risp,
        (data->'field_out')::smallint as field_out,
        (data->'field_out_risp')::smallint as field_out_risp,
        (data->'fielders_choice')::smallint as fielders_choice,
        (data->'fielders_choice_risp')::smallint as fielders_choice_risp,
        (data->'flyouts')::smallint as flyouts,
        (data->'flyouts_risp')::smallint as flyouts_risp,
        (data->'force_outs')::smallint as force_outs,
        (data->'force_outs_risp')::smallint as force_outs_risp,
        (data->'games_finished')::smallint as games_finished,
        (data->'grounded_into_double_play')::smallint as grounded_into_double_play,
        (data->'grounded_into_double_play_risp')::smallint as grounded_into_double_play_risp,
        (data->'groundout')::smallint as groundout,
        (data->'groundout_risp')::smallint as groundout_risp,
        (data->'groundouts')::smallint as groundouts,
        (data->'groundouts_risp')::smallint as groundouts_risp,
        (data->'hit_batters')::smallint as hit_batters,
        (data->'hit_batters_risp')::smallint as hit_batters_risp,
        (data->'hit_by_pitch')::smallint as hit_by_pitch,
        (data->'hit_by_pitch_risp')::smallint as hit_by_pitch_risp,
        (data->'hits_allowed')::smallint as hits_allowed,
        (data->'hits_allowed_risp')::smallint as hits_allowed_risp,
        (data->'home_run_challenge_appearances')::smallint as home_run_challenge_appearances,
        (data->'home_run_challenge_home_runs')::smallint as home_run_challenge_home_runs,
        (data->'home_run_challenge_home_runs_allowed')::smallint as home_run_challenge_home_runs_allowed,
        (data->'home_runs')::smallint as home_runs,
        (data->'home_runs_allowed')::smallint as home_runs_allowed,
        (data->'home_runs_allowed_risp')::smallint as home_runs_allowed_risp,
        (data->'home_runs_risp')::smallint as home_runs_risp,
        (data->'inherited_runners')::smallint as inherited_runners,
        (data->'inherited_runners_risp')::smallint as inherited_runners_risp,
        (data->'inherited_runs_allowed')::smallint as inherited_runs_allowed,
        (data->'inherited_runs_allowed_risp')::smallint as inherited_runs_allowed_risp,
        (data->'left_on_base')::smallint as left_on_base,
        (data->'left_on_base_risp')::smallint as left_on_base_risp,
        (data->'lineouts')::smallint as lineouts,
        (data->'lineouts_risp')::smallint as lineouts_risp,
        (data->'losses')::smallint as losses,
        (data->'mound_visits')::smallint as mound_visits,
        (data->'no_hitters')::smallint as no_hitters,
        (data->'outs')::smallint as outs,
        (data->'perfect_games')::smallint as perfect_games,
        (data->'pitches_thrown')::smallint as pitches_thrown,
        (data->'pitches_thrown_risp')::smallint as pitches_thrown_risp,
        (data->'plate_appearances')::smallint as plate_appearances,
        (data->'plate_appearances_risp')::smallint as plate_appearances_risp,
        (data->'popouts')::smallint as popouts,
        (data->'popouts_risp')::smallint as popouts_risp,
        (data->'putouts')::smallint as putouts,
        (data->'putouts_risp')::smallint as putouts_risp,
        (data->'quality_starts')::smallint as quality_starts,
        (data->'reached_on_error')::smallint as reached_on_error,
        (data->'reached_on_error_risp')::smallint as reached_on_error_risp,
        (data->'runners_caught_stealing')::smallint as runners_caught_stealing,
        (data->'runners_caught_stealing_risp')::smallint as runners_caught_stealing_risp,
        (data->'runs')::smallint as runs,
        (data->'runs_batted_in')::smallint as runs_batted_in,
        (data->'runs_batted_in_risp')::smallint as runs_batted_in_risp,
        (data->'runs_risp')::smallint as runs_risp,
        (data->'sac_flies')::smallint as sac_flies,
        (data->'sac_flies_risp')::smallint as sac_flies_risp,
        (data->'sacrifice_double_plays')::smallint as sacrifice_double_plays,
        (data->'sacrifice_double_plays_risp')::smallint as sacrifice_double_plays_risp,
        (data->'saves')::smallint as saves,
        (data->'shutouts')::smallint as shutouts,
        (data->'singles')::smallint as singles,
        (data->'singles_risp')::smallint as singles_risp,
        (data->'starts')::smallint as starts,
        (data->'stolen_bases')::smallint as stolen_bases,
        (data->'stolen_bases_risp')::smallint as stolen_bases_risp,
        (data->'strikeouts')::smallint as strikeouts,
        (data->'strikeouts_risp')::smallint as strikeouts_risp,
        (data->'struck_out')::smallint as struck_out,
        (data->'struck_out_risp')::smallint as struck_out_risp,
        (data->'triples')::smallint as triples,
        (data->'triples_risp')::smallint as triples_risp,
        (data->'unearned_runs')::smallint as unearned_runs,
        (data->'unearned_runs_risp')::smallint as unearned_runs_risp,
        (data->'walked')::smallint as walked,
        (data->'walked_risp')::smallint as walked_risp,
        (data->'walks')::smallint as walks,
        (data->'walks_risp')::smallint as walks_risp,
        (data->'wins')::smallint as wins
    from game_player_stats
    on conflict (game_id, team_id, player_id) do update set
        player_name = excluded.player_name,
        allowed_stolen_bases = excluded.allowed_stolen_bases,
        allowed_stolen_bases_risp = excluded.allowed_stolen_bases_risp,
        appearances = excluded.appearances,
        assists = excluded.assists,
        assists_risp = excluded.assists_risp,
        at_bats = excluded.at_bats,
        at_bats_risp = excluded.at_bats_risp,
        balks = excluded.balks,
        balks_risp = excluded.balks_risp,
        batters_faced = excluded.batters_faced,
        batters_faced_risp = excluded.batters_faced_risp,
        blown_saves = excluded.blown_saves,
        caught_double_play = excluded.caught_double_play,
        caught_double_play_risp = excluded.caught_double_play_risp,
        caught_stealing = excluded.caught_stealing,
        caught_stealing_risp = excluded.caught_stealing_risp,
        complete_games = excluded.complete_games,
        double_plays = excluded.double_plays,
        double_plays_risp = excluded.double_plays_risp,
        doubles = excluded.doubles,
        doubles_risp = excluded.doubles_risp,
        earned_runs = excluded.earned_runs,
        earned_runs_risp = excluded.earned_runs_risp,
        errors = excluded.errors,
        errors_risp = excluded.errors_risp,
        field_out = excluded.field_out,
        field_out_risp = excluded.field_out_risp,
        fielders_choice = excluded.fielders_choice,
        fielders_choice_risp = excluded.fielders_choice_risp,
        flyouts = excluded.flyouts,
        flyouts_risp = excluded.flyouts_risp,
        force_outs = excluded.force_outs,
        force_outs_risp = excluded.force_outs_risp,
        games_finished = excluded.games_finished,
        grounded_into_double_play = excluded.grounded_into_double_play,
        grounded_into_double_play_risp = excluded.grounded_into_double_play_risp,
        groundout = excluded.groundout,
        groundout_risp = excluded.groundout_risp,
        groundouts = excluded.groundouts,
        groundouts_risp = excluded.groundouts_risp,
        hit_batters = excluded.hit_batters,
        hit_batters_risp = excluded.hit_batters_risp,
        hit_by_pitch = excluded.hit_by_pitch,
        hit_by_pitch_risp = excluded.hit_by_pitch_risp,
        hits_allowed = excluded.hits_allowed,
        hits_allowed_risp = excluded.hits_allowed_risp,
        home_run_challenge_appearances = excluded.home_run_challenge_appearances,
        home_run_challenge_home_runs = excluded.home_run_challenge_home_runs,
        home_run_challenge_home_runs_allowed = excluded.home_run_challenge_home_runs_allowed,
        home_runs = excluded.home_runs,
        home_runs_allowed = excluded.home_runs_allowed,
        home_runs_allowed_risp = excluded.home_runs_allowed_risp,
        home_runs_risp = excluded.home_runs_risp,
        inherited_runners = excluded.inherited_runners,
        inherited_runners_risp = excluded.inherited_runners_risp,
        inherited_runs_allowed = excluded.inherited_runs_allowed,
        inherited_runs_allowed_risp = excluded.inherited_runs_allowed_risp,
        left_on_base = excluded.left_on_base,
        left_on_base_risp = excluded.left_on_base_risp,
        lineouts = excluded.lineouts,
        lineouts_risp = excluded.lineouts_risp,
        losses = excluded.losses,
        mound_visits = excluded.mound_visits,
        no_hitters = excluded.no_hitters,
        outs = excluded.outs,
        perfect_games = excluded.perfect_games,
        pitches_thrown = excluded.pitches_thrown,
        pitches_thrown_risp = excluded.pitches_thrown_risp,
        plate_appearances = excluded.plate_appearances,
        plate_appearances_risp = excluded.plate_appearances_risp,
        popouts = excluded.popouts,
        popouts_risp = excluded.popouts_risp,
        putouts = excluded.putouts,
        putouts_risp = excluded.putouts_risp,
        quality_starts = excluded.quality_starts,
        reached_on_error = excluded.reached_on_error,
        reached_on_error_risp = excluded.reached_on_error_risp,
        runners_caught_stealing = excluded.runners_caught_stealing,
        runners_caught_stealing_risp = excluded.runners_caught_stealing_risp,
        runs = excluded.runs,
        runs_batted_in = excluded.runs_batted_in,
        runs_batted_in_risp = excluded.runs_batted_in_risp,
        runs_risp = excluded.runs_risp,
        sac_flies = excluded.sac_flies,
        sac_flies_risp = excluded.sac_flies_risp,
        sacrifice_double_plays = excluded.sacrifice_double_plays,
        sacrifice_double_plays_risp = excluded.sacrifice_double_plays_risp,
        saves = excluded.saves,
        shutouts = excluded.shutouts,
        singles = excluded.singles,
        singles_risp = excluded.singles_risp,
        starts = excluded.starts,
        stolen_bases = excluded.stolen_bases,
        stolen_bases_risp = excluded.stolen_bases_risp,
        strikeouts = excluded.strikeouts,
        strikeouts_risp = excluded.strikeouts_risp,
        struck_out = excluded.struck_out,
        struck_out_risp = excluded.struck_out_risp,
        triples = excluded.triples,
        triples_risp = excluded.triples_risp,
        unearned_runs = excluded.unearned_runs,
        unearned_runs_risp = excluded.unearned_runs_risp,
        walked = excluded.walked,
        walked_risp = excluded.walked_risp,
        walks = excluded.walks,
        walks_risp = excluded.walks_risp,
        wins = excluded.wins;

-- make indexes last
create index game_player_stats_exploded_by_player_idx on game_player_stats_exploded(player_id, season, day);
create index game_player_stats_exploded_by_team_idx on game_player_stats_exploded(team_id, season, day);
create index game_player_stats_exploded_by_season_day_idx on game_player_stats_exploded(season, day);
