import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { getQueryClient } from "@/get-query-client";
import { dehydrate, HydrationBoundary } from "@tanstack/react-query";

// import "@mantine/core/styles.css";

import SiteHeader from "@/components/SiteHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const queryClient = getQueryClient();
  // queryClient.prefetchQuery({
  //     queryKey: ["teams"],
  //     queryFn: async () => {
  //         return fetch("https://freecashe.ws/api/allteams").then(r => r.json())
  //     },
  // });

  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-[family-name:var(--font-geist-sans)] antialiased`}
      >
        <Providers>
          <SiteHeader />
          <div className="container mx-auto p-4">{children}</div>
        </Providers>
      </body>
    </html>
  );
}
